version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: SpeedRunningLeaderboardsWebApi/Dockerfile
    depends_on:
      - sql
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
  api-gateway:
      build:
        context: .
        dockerfile: nginx.Dockerfile
      depends_on:
        - frontend
        - backend
      ports:
        - 8080:9090
  redis:
    image: "redis:alpine"
  sql:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          SA_PASSWORD: "Password123!"
          ACCEPT_EULA: "Y"
