CREATE TABLE dbo.ColumnValue
(
	ColumnValueID GUID NOT NULL PRIMARY KEY,
	RunID GUID NOT NULL FOREIGN KEY
		REFERENCES dbo.Run(RunID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	ColumnID GUID NOT NULL FOREIGN KEY
		REFERENCES dbo.[Column](ColumnID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	[Value] VARCHAR(max) NULL
);