CREATE TABLE dbo.Ruleset
(
	RulesetID GUID NOT NULL PRIMARY KEY,
	GameID GUID NOT NULL FOREIGN KEY
		REFERENCES dbo.Game(GameID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	Title NVARCHAR(64) NOT NULL,
	[Description] NVARCHAR(max) NOT NULL
);