CREATE TABLE dbo.Run
(
	RunID GUID NOT NULL PRIMARY KEY,
	RunnerID GUID NOT NULL FOREIGN KEY
		REFERENCES dbo.Runner(RunnerID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	ServerID GUID NOT NULL FOREIGN KEY
		REFERENCES dbo.[Server](ServerID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	PublishDate DATETIME NOT NULL,
	RunTime DECIMAL NOT NULL,
	VideoURL URL NOT NULL 
);