CREATE TABLE dbo.ServerMembers
(
	ServerMemberID INT NOT NULL PRIMARY KEY IDENTITY(0, 1),
	RunnerID GUID NOT NULL FOREIGN KEY
		REFERENCES dbo.Runner(RunnerID)
			ON DELETE CASCADE
			ON UPDATE CASCADE,
	ServerID GUID NOT NULL FOREIGN KEY
		REFERENCES dbo.[Server](ServerID)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);