CREATE TABLE dbo.Server
(
	ServerID GUID NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(24) NOT NULL,
	Icon VARCHAR(256) NOT NULL,
	[Owner] GUID NOT NULL FOREIGN KEY
		REFERENCES dbo.Runner(RunnerID)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);