CREATE TABLE dbo.Social
(
	SocialID GUID NOT NULL PRIMARY KEY,
	RunnerID GUID NOT NULL FOREIGN KEY
		REFERENCES dbo.Runner(RunnerID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	IconEndpoint VARCHAR(256) NOT NULL,
	[URL] URL
);