CREATE TABLE dbo.Social
(
	SocialID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	RunnerID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
		REFERENCES dbo.Runner(RunnerID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	IconEndpoint VARCHAR(256) NOT NULL,
	[URL] VARCHAR(2048)
);