IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'Chat' AND xtype='U')
CREATE TABLE dbo.Chat
(
	ChatID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(24) NOT NULL,
	ServerID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
		REFERENCES dbo.[Server](ServerID)
);