IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'Game' AND xtype='U')
	CREATE TABLE dbo.Game
	(
		GameID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
		Title NVARCHAR(64) NOT NULL,
		Rules NVARCHAR(MAX) NOT NULL,
		[Image] VARCHAR(2048) NOT NULL
	);