IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'Message' AND xtype='U')
CREATE TABLE dbo.[Message]
(
	MessageID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	ChatID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
		REFERENCES dbo.Chat(ChatID),
	PosterID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
		REFERENCES dbo.Runner(RunnerID),
	PublishDate DATETIME NOT NULL,
	Content NVARCHAR(max) NOT NULL
);