CREATE TABLE dbo.Moderator
(
	ModerationID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	RunnerID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
		REFERENCES dbo.Runner(RunnerID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	GameID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
		REFERENCES dbo.Game(GameID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	ServerID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
		REFERENCES dbo.Server(ServerID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	IsLeadMod BIT NOT NULL
);