IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'Moderator' AND xtype='U')
	CREATE TABLE dbo.Moderator
	(
		ModerationID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
		RunnerID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
			REFERENCES dbo.Runner(RunnerID),
		GameID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
			REFERENCES dbo.Game(GameID),
		ServerID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
			REFERENCES dbo.Server(ServerID),
		IsLeadMod BIT NOT NULL
	);