CREATE TABLE dbo.Run
(
	RunID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	RunnerID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
		REFERENCES dbo.Runner(RunnerID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	ServerID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
		REFERENCES dbo.[Server](ServerID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	PublishDate DATETIME NOT NULL,
	RunTime DECIMAL NOT NULL,
	VideoURL VARCHAR(2048) NOT NULL 
);