IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'ServerMembers' AND xtype='U')
	CREATE TABLE dbo.ServerMembers
	(
		ServerMemberID INT NOT NULL PRIMARY KEY IDENTITY(0, 1),
		RunnerID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
			REFERENCES dbo.Runner(RunnerID),
		ServerID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY
			REFERENCES dbo.[Server](ServerID)
				ON DELETE CASCADE
				ON UPDATE CASCADE
	);